server:
 port: 8090
spring:
 cloud:
  config:
   server:
    git:
     uri: https://github.com/luegmy/GageSpringCloudCinfig
     searchPaths: config-data
     username: ${GIT_USER}
     password: ${GIT_PASSWORD}
 security:
    user:
      name: root
      password: s3cr3t
     
  
